version: 2.1

orbs:
  silta: silta/silta@0.1

executors:
  cicd81:
    docker:
      - image: wunderio/silta-cicd:circleci-php8.1-node16-composer2-v0.1
    resource_class: small

workflows:
  version: 2
  commit:
    jobs:
      - silta/drupal-validate:
          name: validate
          executor: cicd81
          drupal-root: "drupal"
          web-root: "drupal/web"
          post-validation:
            - run: echo "You can add additional validation here!"

      - silta/analyze:
          name: analyze
          context: analyze
          sources: drupal/web

      - silta/drupal-build-deploy: &build-deploy
          name: Drupal build & deploy
          executor: cicd81
          drupal-root: drupal
          codebase-build:
            - run: cp -r ~/project/silta ~/project/drupal/
            - silta/drupal-composer-install
            - silta/npm-install-build
          context: silta_dev
          filters:
            branches:
              ignore:
                - production
                - /dependabot\/.*/

      - silta/drupal-build-deploy:
          # Extend the build-deploy configuration for the production environment.
          <<: *build-deploy
          name: Drupal build & deploy production
          silta_config: silta/silta.yml,silta/silta-prod.yml
          context: silta_finland
          filters:
            branches:
              only: production

      - silta/drupal-build-deploy:
          <<: *build-deploy
          name: Drupal build dependabot 
          context: silta_dev
          skip-deployment: true
          filters:
            branches:
              only: /dependabot\/.*/

      # silta/frontend-build-deploy is defined here https://github.com/wunderio/silta-circleci/blob/master/orb/jobs/%40frontend.yml
      # &build-deploy is a yaml anchor, so we can reference it later
      - silta/frontend-build-deploy: &frontend-build-deploy
          name: Next build & deploy
          context: silta_dev
          silta_config: silta/silta-next.yml
          codebase-build:
            # npm-install-build command is defined here https://github.com/wunderio/silta-circleci/blob/master/orb/commands/@npm.yml
            - run:
                name: Set environment variables 
                command: |
                  # Make sure release name is lowercase without special characters.
                  branchname_lower="${CIRCLE_BRANCH,,}"
                  release_name="${branchname_lower//[^[:alnum:]]/-}"
                  release_name=`echo $release_name | sed -e s/-next//`
                  # If name is too long, truncate it and append a hash
                  if [ ${#release_name} -ge 35 ]; then
                    release_name="$(printf "$release_name" | cut -c 1-34)$(printf "$release_name" | shasum -a 256 | cut -c 1-3 )"
                  fi
                  next_image_domain=`echo $release_name`.$CIRCLE_PROJECT_REPONAME.$CLUSTER_DOMAIN
                  echo "export NEXT_PUBLIC_DRUPAL_BASE_URL=https://${next_image_domain}" >> "$BASH_ENV"
                  echo "export NEXT_IMAGE_DOMAIN=${next_image_domain}" >> "$BASH_ENV"
                  echo "export DRUPAL_CLIENT_SECRET=uj1M/+Ovd88DsvHR2xBXuQE2Z7o=" >> "$BASH_ENV"
                  echo "export DRUPAL_CLIENT_ID=b7302bd7-f2b6-43b6-ae6f-d1b47c44cf54" >> "$BASH_ENV"
            - silta/npm-install-build:
                path: next
            - silta/build-docker-image:
                dockerfile: 'silta/node.Dockerfile'
                path: './next'
                identifier: 'next '
                docker-hash-prefix: v1
          filters:
            branches:
              ignore:
                - production
                - /dependabot\/.*/


      - silta/frontend-build-deploy:
          # Extend the build-deploy configuration for the production environment.
          <<: *frontend-build-deploy
          name: Next build & deploy production
          context: silta_finland
          silta_config: silta/silta-next.yml,silta/silta-next-prod.yml
          filters:
            branches:
              only: production

      - silta/frontend-build-deploy:
          <<: *frontend-build-deploy
          name: Next Build Dependabot
          context: silta_dev
          skip-deployment: true
          filters:
            branches:
              only: /dependabot\/.*/
